version: '3'

services:
  mysql:
    image: willywijayaa/popsicle-mysql:1.0
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: popsicle
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  node-app:
    image: willywijayaa/popsicle:1.0
    container_name: popsicle-container
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - mynetwork
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB: popsicle
      DB_PASSWORD: password
      DB_PORT: 3306
    depends_on:
      - mysql

networks:
  mynetwork:
    driver: bridge
